### ISSUE TITLE
Errors when execute "launch.sh -all" in rcrs-adf-sample.

### ISSUE THREAD

**Issue by June8144** [roborescue/adf-sample-agent-java#24]
It points out that

[ RCRS ADF Version 2.3.0 (build 20200403013538) ]

[adf.sample.SampleLoader, -t, -1,-1,-1,-1,-1,-1]
Exception in thread "main" java.lang.NumberFormatException: For input string: "adf.sample.SampleLoader"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:668)
        at java.base/java.lang.Integer.parseInt(Integer.java:786)
        at adf.Main.main(Main.java:25)

So, do you know how to solve it?
![图片](https://github.com/roborescue/adf-sample-agent-java/assets/142232794/7c4cea6b-554a-412f-9e3c-46893a0c7713)

**Comment by gnardin** [comment]
Dear @June8144 

I could not reproduce your issue. I cloned the repository, built the project and executed the `launch.sh` successfully. Please try the following sequence to see if you still find the problem:

```
git clone https://github.com/roborescue/adf-sample-agent-java.git
cd adf-sample-agent-java
./gradlew clean
./gradlew build
./launch.sh -all
```

**NOTE**: Before running the `./launch.sh` command, you should have the RCRS Server running.

In the screenshot, the message reads `adf.sample.SampleLoader`, but the default Loader in the `launch.sh` is `adf.impl.DefaultLoader`. Have you changed anything in the `launch.sh`?
